version : 0.2 

phases: 
  install:
    runtime-versions:
      python: 3.11
    commands:
    - echo "installing Terraform"
    - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
    - unzip terraform.zip -d /usr/local/bin/
  
  build:
    commands:
      - terraform init
      - terraform plan -out tfplan
      - terraform apply -auto-approve tfplan